server.port=8443
server.context.path=/
server.endpoint.path=/socket
server.keystore.path=/app/keystore.p12
server.keystore.password=password
server.inbox.schedule.intervalMillis=25
server.outbox.schedule.intervalMillis=25

proudlobster.email.account=admin@proudlobster.com
proudlobster.email.password=ThisIsEmailAccountForProudLobste
proudlobster.email.host=mail.privateemail.com
proudlobster.email.port=587

script.js.paths.base=script
script.js.paths.common=common
script.js.paths.processor=processor
script.js.paths.command=command
script.js.paths.bootstrap=bootstrap
script.js.paths.component=component

processor.schedule.intervalMillis=10