server.port=8443
server.context.path=/
server.endpoint.path=/socket
server.keystore.path=/app/keystore.p12
server.keystore.password=
server.inbox.schedule.intervalMillis=25
server.outbox.schedule.intervalMillis=25

proudlobster.email.account=admin@proudlobster.com
proudlobster.email.password=
proudlobster.email.host=mail.privateemail.com
proudlobster.email.port=587

script.js.paths.base=/app/scripts
script.js.paths.common=common
script.js.paths.processor=processor
script.js.paths.command=command
script.js.paths.bootstrap=bootstrap
script.js.paths.component=component

processor.schedule.intervalMillis=100

storage.snapshot.intervalMillis=1800000
storage.activity.intervalMillis=60000
storage.datasource.className=com.mysql.cj.jdbc.MysqlDataSource
storage.datasource.properties=user,password,serverName,databaseName
storage.datasource.prop.databaseName=WUMPUS_DB
storage.datasource.prop.user=wumpus
storage.datasource.prop.serverName=wumpus-database